project_id = "yqpqfjmyghoehxzuevrz"

[functions.send-auth-email]
verify_jwt = false

[functions.notify-new-signup]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = true

[functions.sitemap]
verify_jwt = false

[functions.fetch-federal-register]
verify_jwt = false

[functions.fetch-msha-fatalities]
verify_jwt = false

[functions.fetch-market-data]
verify_jwt = false
