-- Add Final Assessment for Module 2
INSERT INTO lessons (module_id, title, description, type, order_index, duration_minutes, is_required, content_data)
VALUES (
  '49d3c048-b3bf-41a2-9fb0-a8084c758efc',
  'Module 2: Final Knowledge Assessment',
  'A comprehensive 20-question assessment testing your understanding of hazard recognition, LOTO procedures, ground control, and mobile equipment safety.',
  'quiz',
  6,
  15,
  true,
  jsonb_build_object(
    'instructions', 'This assessment consists of 20 questions covering all units of Module 2. A passing score of 80% (16 out of 20 correct) is required to successfully complete this module. Upon successful completion, your training will be certified and recorded on MSHA Form 5000-23.',
    'passingScore', 80,
    'questions', jsonb_build_array(
      jsonb_build_object('question', 'What is the primary federal law that governs health and safety in the mining industry?', 'options', jsonb_build_array('Occupational Safety and Health Act (OSHA)', 'Federal Mine Safety and Health Act of 1977', 'Surface Mining Control and Reclamation Act', 'National Mining and Minerals Policy Act'), 'correctAnswer', 1),
      jsonb_build_object('question', 'According to MSHA fatality data analysis, which hazard category is consistently the leading cause of fatal accidents in surface mining?', 'options', jsonb_build_array('Electrical hazards', 'Powered haulage', 'Ground control failures', 'Machinery entanglement'), 'correctAnswer', 1),
      jsonb_build_object('question', 'What is the first step in the "See, Think, Act" hazard recognition cycle?', 'options', jsonb_build_array('Think about the consequences', 'Act to control the hazard', 'See the hazard by actively scanning your work area', 'Report the hazard to your supervisor'), 'correctAnswer', 2),
      jsonb_build_object('question', 'What is the primary function of a properly designed safety grounding system?', 'options', jsonb_build_array('To connect all equipment to the earth', 'To provide a low-impedance path for fault current to return to the power source', 'To prevent static electricity buildup', 'To reduce the voltage of the electrical system'), 'correctAnswer', 1),
      jsonb_build_object('question', 'In a proper LOTO procedure, what is the final and most critical verification step?', 'options', jsonb_build_array('Applying your personal lock to the disconnect', 'Notifying all affected employees', 'Attempting to start the equipment to verify zero-energy state (the "Try" step)', 'Reading the equipment manual'), 'correctAnswer', 2),
      jsonb_build_object('question', 'What type of electrical event can create temperatures exceeding 35,000°F and cause severe burns?', 'options', jsonb_build_array('Electric shock', 'Arc flash', 'Ground fault', 'Static discharge'), 'correctAnswer', 1),
      jsonb_build_object('question', 'Which MSHA standard is a "Rule to Live By" that mandates proper procedures for work on power circuits?', 'options', jsonb_build_array('§56.12017', '§56.14105', '§56.14131(a)', '§56.3401'), 'correctAnswer', 0),
      jsonb_build_object('question', 'What is a tension crack in relation to highwall stability?', 'options', jsonb_build_array('A crack caused by equipment vibration', 'A crack running parallel to the edge of the highwall crest indicating potential failure', 'A crack at the base of the highwall', 'A crack caused by blasting operations'), 'correctAnswer', 1),
      jsonb_build_object('question', 'What is the "angle of repose" for granular materials?', 'options', jsonb_build_array('The angle at which a pile becomes unstable and collapses', 'The angle of a highwall face', 'The angle of a haul road grade', 'The angle at which water drains from a stockpile'), 'correctAnswer', 0),
      jsonb_build_object('question', 'Why is it extremely dangerous to load material from the toe (bottom) of an active stockpile?', 'options', jsonb_build_array('It makes the loader difficult to see', 'It undercuts the pile, making it unstable and creating an engulfment hazard', 'It damages the loader bucket', 'It reduces production efficiency'), 'correctAnswer', 1),
      jsonb_build_object('question', 'When working on, over, or near water where there is a danger of falling in, what is the most critical piece of PPE?', 'options', jsonb_build_array('Steel-toed boots', 'Hard hat', 'U.S. Coast Guard-approved Personal Flotation Device (PFD)', 'Safety glasses'), 'correctAnswer', 2),
      jsonb_build_object('question', 'What should you do when you see water seeping from the face of a highwall?', 'options', jsonb_build_array('Ignore it if it is a small amount', 'Report it immediately as it indicates decreased stability', 'Wait until the end of your shift to report it', 'Try to redirect the water yourself'), 'correctAnswer', 1),
      jsonb_build_object('question', 'What is a "blind spot" or "blind area" in relation to mobile equipment?', 'options', jsonb_build_array('An area that is poorly lit', 'An area not visible to the operator through direct sight or mirrors', 'An area where the ground is unstable', 'An area restricted by management'), 'correctAnswer', 1),
      jsonb_build_object('question', 'What is the cardinal rule when approaching a piece of mobile equipment on foot?', 'options', jsonb_build_array('Approach quickly to minimize time in the danger zone', 'Assume the operator can see you at all times', 'Never approach until you have made positive eye contact with the operator and received acknowledgment', 'Always approach from the rear of the vehicle'), 'correctAnswer', 2),
      jsonb_build_object('question', 'What is the primary role of a spotter when guiding mobile equipment?', 'options', jsonb_build_array('To direct traffic for other vehicles', 'To act as the operator''s eyes and ears on the ground to ensure safe movement', 'To inspect the equipment for defects', 'To load and unload materials'), 'correctAnswer', 1),
      jsonb_build_object('question', 'If an equipment operator loses sight of the spotter during a maneuver, what must the operator do immediately?', 'options', jsonb_build_array('Continue slowly and carefully', 'Sound the horn', 'Stop the equipment immediately', 'Radio for a new spotter'), 'correctAnswer', 2),
      jsonb_build_object('question', 'What is the leading cause of entanglement accidents involving belt conveyors?', 'options', jsonb_build_array('Lack of operator training', 'Contact with ingoing nip points at pulleys and rollers', 'Electrical malfunctions', 'Overloading the belt'), 'correctAnswer', 1),
      jsonb_build_object('question', 'Before performing any maintenance on a conveyor system, what critical safety procedure must be performed?', 'options', jsonb_build_array('Notify the shift supervisor only', 'Perform a full LOTO procedure and block the belt against motion', 'Slow the belt speed down', 'Post a warning sign'), 'correctAnswer', 1),
      jsonb_build_object('question', 'According to MSHA standards, what percentage of lost-time accidents are caused by slips, trips, and falls combined with material handling?', 'options', jsonb_build_array('Approximately 20%', 'Approximately 40%', 'Approximately 60%', 'Approximately 80%'), 'correctAnswer', 2),
      jsonb_build_object('question', 'What is your primary responsibility regarding blasting operations if you are not a trained and authorized blaster?', 'options', jsonb_build_array('Inspect the blast area after detonation', 'Help set the charges', 'Hazard avoidance: obey warning signals and stay out of restricted blast areas', 'Dispose of unused explosives'), 'correctAnswer', 2)
    )
  )
);