-- Add questions 21-40 (Module 3 & Module 4)
UPDATE lessons
SET content_data = jsonb_set(
  content_data,
  '{questions}',
  content_data->'questions' || jsonb_build_array(
    -- Questions 21-30 (Module 3: Emergency Procedures)
    jsonb_build_object('id', 'q21', 'question', 'In an emergency, who is the single individual responsible for managing the entire response?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'The most experienced miner on site'), jsonb_build_object('id', 'b', 'text', 'The safety manager, regardless of their location'), jsonb_build_object('id', 'c', 'text', 'The Incident Commander (IC), usually the senior supervisor on site'), jsonb_build_object('id', 'd', 'text', 'The first miner to report the incident')), 'correctAnswer', 'c', 'explanation', 'The Incident Commander (IC) has ultimate authority and responsibility for managing an emergency response.'),
    jsonb_build_object('id', 'q22', 'question', 'What is the correct procedure for using a portable fire extinguisher, according to the P.A.S.S. method?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Point, Aim, Squeeze, Spray'), jsonb_build_object('id', 'b', 'text', 'Pull, Aim, Squeeze, Sweep'), jsonb_build_object('id', 'c', 'text', 'Pass by the fire, Alert others, Stay calm, Secure the area'), jsonb_build_object('id', 'd', 'text', 'Pull, Activate, Spray, Stop')), 'correctAnswer', 'b', 'explanation', 'Pull, Aim, Squeeze, Sweep is the correct and universally taught method for using an extinguisher.'),
    jsonb_build_object('id', 'q23', 'question', 'You are trying to escape from a submerged vehicle cab. Why should you wait for the cab to almost completely fill with water before trying to exit through a window?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'To give rescue divers time to arrive'), jsonb_build_object('id', 'b', 'text', 'To allow the vehicle to settle on the bottom'), jsonb_build_object('id', 'c', 'text', 'To equalize the pressure, making it possible to break a window and exit'), jsonb_build_object('id', 'd', 'text', 'To conserve your body heat in the cold water')), 'correctAnswer', 'c', 'explanation', 'Trying to open a door or break a window against external water pressure is nearly impossible. Waiting for the pressure to equalize by letting the cab fill is the correct, though counter-intuitive, survival technique.'),
    jsonb_build_object('id', 'q24', 'question', 'A coworker has been trapped under a large rock for 30 minutes. You know this is a potential Crush Syndrome situation. What should you NOT do?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Call 911 and report a "prolonged crush injury"'), jsonb_build_object('id', 'b', 'text', 'Keep the victim warm and offer reassurance'), jsonb_build_object('id', 'c', 'text', 'Immediately use equipment to lift the rock and free the victim'), jsonb_build_object('id', 'd', 'text', 'Control any accessible bleeding')), 'correctAnswer', 'c', 'explanation', 'Releasing the pressure after prolonged entrapment can cause a fatal surge of toxins (Crush Syndrome). The victim requires advanced medical care before extrication.'),
    jsonb_build_object('id', 'q25', 'question', 'What is the purpose of a designated rally point (muster point)?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'To store emergency response equipment'), jsonb_build_object('id', 'b', 'text', 'To provide a safe location for personnel to assemble for an accurate headcount after an evacuation'), jsonb_build_object('id', 'c', 'text', 'To serve as the primary first aid station'), jsonb_build_object('id', 'd', 'text', 'To be a shelter during blasting operations')), 'correctAnswer', 'b', 'explanation', 'The rally point is a pre-designated safe location for evacuation and accountability.'),
    jsonb_build_object('id', 'q26', 'question', 'You hear a series of short horn blasts, which is the site''s blasting alarm. What is the required action?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Stop work and wait for the "all clear" signal'), jsonb_build_object('id', 'b', 'text', 'Immediately evacuate the designated blast zone and take cover in an engineered blast shelter'), jsonb_build_object('id', 'c', 'text', 'Move all mobile equipment to the base of the highwall for protection'), jsonb_build_object('id', 'd', 'text', 'Get on the radio and ask the blaster for more information')), 'correctAnswer', 'b', 'explanation', 'A blasting alarm requires immediate evacuation of the blast zone to a proper, engineered shelter. A vehicle is not a safe shelter.'),
    jsonb_build_object('id', 'q27', 'question', 'The standardized L.I.P. protocol for reporting an emergency over the radio stands for:', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Look, Identify, Proceed'), jsonb_build_object('id', 'b', 'text', 'Listen, Investigate, Problem'), jsonb_build_object('id', 'c', 'text', 'Location, Identification, Problem'), jsonb_build_object('id', 'd', 'text', 'Loud, Immediate, Precise')), 'correctAnswer', 'c', 'explanation', 'Location, Identification, Problem is the standardized protocol for clear and efficient emergency communication.'),
    jsonb_build_object('id', 'q28', 'question', 'If you suspect a victim has a spinal injury, what is the most important principle to follow?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Immediately sit them up to help them breathe'), jsonb_build_object('id', 'b', 'text', 'Do not move the victim unless they are in immediate danger'), jsonb_build_object('id', 'c', 'text', 'Place a blanket under their head for comfort'), jsonb_build_object('id', 'd', 'text', 'Ask them to try and stand up to check for injury')), 'correctAnswer', 'b', 'explanation', 'The primary rule for a suspected spinal injury is to immobilize the victim and prevent any movement of the head, neck, or back.'),
    jsonb_build_object('id', 'q29', 'question', 'When fighting a vehicle fire with a portable extinguisher, where should you aim the nozzle?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'At the top of the flames'), jsonb_build_object('id', 'b', 'text', 'At the center of the fire'), jsonb_build_object('id', 'c', 'text', 'At the base of the fire'), jsonb_build_object('id', 'd', 'text', 'Into the operator''s cab')), 'correctAnswer', 'c', 'explanation', 'Aiming at the base of the fire attacks the fuel source and is the most effective way to extinguish it.'),
    jsonb_build_object('id', 'q30', 'question', 'In the event of a blasting misfire, what is the correct procedure?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'The blaster should immediately approach the shot to check the wiring'), jsonb_build_object('id', 'b', 'text', 'All personnel must remain in a secure blast shelter for a designated waiting period'), jsonb_build_object('id', 'c', 'text', 'Use a piece of mobile equipment to nudge the shot and see if it detonates'), jsonb_build_object('id', 'd', 'text', 'Immediately try to fire the shot again using a different power source')), 'correctAnswer', 'b', 'explanation', 'A misfire is an extremely dangerous situation. All personnel must retreat to a safe shelter for a specified waiting period before any troubleshooting begins.'),
    
    -- Questions 31-40 (Module 4: Health and Chemical Safety)
    jsonb_build_object('id', 'q31', 'question', 'What is the most common and dangerous route of entry for airborne contaminants like silica dust?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Absorption'), jsonb_build_object('id', 'b', 'text', 'Ingestion'), jsonb_build_object('id', 'c', 'text', 'Injection'), jsonb_build_object('id', 'd', 'text', 'Inhalation')), 'correctAnswer', 'd', 'explanation', 'Inhalation is the most direct and common way for harmful dusts and vapors to enter the body and cause damage.'),
    jsonb_build_object('id', 'q32', 'question', 'On a GHS-compliant label, which signal word is used for the most severe hazards?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Warning'), jsonb_build_object('id', 'b', 'text', 'Caution'), jsonb_build_object('id', 'c', 'text', 'Danger'), jsonb_build_object('id', 'd', 'text', 'Notice')), 'correctAnswer', 'c', 'explanation', '"Danger" is used for the most severe hazards, while "Warning" is used for less severe hazards.'),
    jsonb_build_object('id', 'q33', 'question', 'Where would you find the most detailed information on the required Personal Protective Equipment (PPE) for a specific chemical?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'On the purchase order for the chemical'), jsonb_build_object('id', 'b', 'text', 'In the mine''s emergency action plan'), jsonb_build_object('id', 'c', 'text', 'In Section 8 of the Safety Data Sheet (SDS)'), jsonb_build_object('id', 'd', 'text', 'On the container''s GHS label')), 'correctAnswer', 'c', 'explanation', 'Section 8 of the SDS, "Exposure Controls/Personal Protection," provides detailed specifications for required PPE.'),
    jsonb_build_object('id', 'q34', 'question', 'Silicosis is an incurable lung disease caused by long-term exposure to:', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Diesel Particulate Matter (DPM)'), jsonb_build_object('id', 'b', 'text', 'Welding fumes'), jsonb_build_object('id', 'c', 'text', 'Respirable Crystalline Silica (RCS)'), jsonb_build_object('id', 'd', 'text', 'Asbestos fibers')), 'correctAnswer', 'c', 'explanation', 'Respirable Crystalline Silica (RCS) particles cause irreversible scarring of the lungs, known as silicosis.'),
    jsonb_build_object('id', 'q35', 'question', 'According to the Hierarchy of Controls, what is the most effective way to control a hazard?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Using Personal Protective Equipment (PPE)'), jsonb_build_object('id', 'b', 'text', 'Implementing administrative controls like job rotation'), jsonb_build_object('id', 'c', 'text', 'Using engineering controls to isolate people from the hazard'), jsonb_build_object('id', 'd', 'text', 'Elimination or substitution of the hazard')), 'correctAnswer', 'd', 'explanation', 'The most effective control is to eliminate the hazard entirely or substitute it with something safer.'),
    jsonb_build_object('id', 'q36', 'question', 'Before you can be required to wear a tight-fitting respirator, your employer must provide you with a medical evaluation and what other critical procedure?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'A hearing test'), jsonb_build_object('id', 'b', 'text', 'A fit test'), jsonb_build_object('id', 'c', 'text', 'A drug screening'), jsonb_build_object('id', 'd', 'text', 'A background check')), 'correctAnswer', 'b', 'explanation', 'A fit test is mandatory to ensure the respirator can form a tight seal against the user''s face, without which it offers no protection.'),
    jsonb_build_object('id', 'q37', 'question', 'A coworker splashes a corrosive chemical in their eyes. What is the most critical first aid action?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Have them lie down and cover their eyes with a clean cloth'), jsonb_build_object('id', 'b', 'text', 'Immediately flush eyes with clean water for at least 15 minutes while holding eyelids open'), jsonb_build_object('id', 'c', 'text', 'Call for emergency medical help first before doing anything'), jsonb_build_object('id', 'd', 'text', 'Try to neutralize the chemical with a different substance')), 'correctAnswer', 'b', 'explanation', 'Immediate and prolonged flushing with water is the critical first aid step to minimize damage from a chemical eye exposure.'),
    jsonb_build_object('id', 'q38', 'question', 'The MSHA Action Level for noise exposure, which requires enrollment in a Hearing Conservation Program, is an 8-hour time-weighted average of:', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', '80 dBA'), jsonb_build_object('id', 'b', 'text', '85 dBA'), jsonb_build_object('id', 'c', 'text', '90 dBA'), jsonb_build_object('id', 'd', 'text', '105 dBA')), 'correctAnswer', 'b', 'explanation', 'Exposure at or above 85 dBA over an 8-hour TWA triggers the requirement for an operator to enroll a miner in a Hearing Conservation Program.'),
    jsonb_build_object('id', 'q39', 'question', 'What is the primary health risk associated with long-term exposure to Whole-Body Vibration (WBV) from operating heavy equipment?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Hearing loss'), jsonb_build_object('id', 'b', 'text', 'Carpal tunnel syndrome'), jsonb_build_object('id', 'c', 'text', 'Chronic low-back pain and musculoskeletal disorders'), jsonb_build_object('id', 'd', 'text', 'Respiratory illness')), 'correctAnswer', 'c', 'explanation', 'The constant jarring from operating heavy equipment over rough terrain is a primary cause of chronic back injuries and other MSDs.'),
    jsonb_build_object('id', 'q40', 'question', 'The GHS pictogram showing a flame over a circle represents what type of hazard?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Flammable'), jsonb_build_object('id', 'b', 'text', 'Explosive'), jsonb_build_object('id', 'c', 'text', 'Oxidizer'), jsonb_build_object('id', 'd', 'text', 'Corrosive')), 'correctAnswer', 'c', 'explanation', 'The flame-over-circle pictogram specifically indicates an oxidizing hazard, meaning the substance can cause or intensify a fire.')
  )
),
updated_at = now()
WHERE id = 'd4e5f6a7-b8c9-4444-5555-666677778888';