-- Add final questions 41-50 (Module 5: Miners' Rights)
UPDATE lessons
SET content_data = jsonb_set(
  content_data,
  '{questions}',
  content_data->'questions' || jsonb_build_array(
    -- Questions 41-50 (Module 5: Miners' Rights, Responsibilities, and Final Review)
    jsonb_build_object('id', 'q41', 'question', 'The Federal Mine Safety and Health Act of 1977 is also known as:', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'The OSHA Act'), jsonb_build_object('id', 'b', 'text', 'The Miner''s Bill of Rights'), jsonb_build_object('id', 'c', 'text', 'The Mine Act'), jsonb_build_object('id', 'd', 'text', 'The Surface Mining Control Act')), 'correctAnswer', 'c', 'explanation', 'The legislation is officially titled the Federal Mine Safety and Health Act of 1977, commonly called "the Mine Act".'),
    jsonb_build_object('id', 'q42', 'question', 'You have a "good faith, reasonable belief" that a task is unsafe. What is the first thing you must do when exercising your right to refuse unsafe work?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Call the MSHA hotline immediately'), jsonb_build_object('id', 'b', 'text', 'Leave the mine site and go home'), jsonb_build_object('id', 'c', 'text', 'Immediately notify your supervisor of the hazard and your refusal to work'), jsonb_build_object('id', 'd', 'text', 'Discuss the issue with your coworkers to see if they agree')), 'correctAnswer', 'c', 'explanation', 'Notifying the supervisor is the mandatory first step that initiates the protected work refusal process.'),
    jsonb_build_object('id', 'q43', 'question', 'Section 105(c) of the Mine Act protects you from:', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'On-the-job injuries'), jsonb_build_object('id', 'b', 'text', 'Exposure to loud noises'), jsonb_build_object('id', 'c', 'text', 'Discrimination or retaliation for exercising your safety rights'), jsonb_build_object('id', 'd', 'text', 'Having to work overtime')), 'correctAnswer', 'c', 'explanation', 'Section 105(c) is the specific anti-retaliation provision of the Mine Act.'),
    jsonb_build_object('id', 'q44', 'question', 'How long do you have to file a discrimination complaint with MSHA after an alleged retaliatory action occurs?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', '30 days'), jsonb_build_object('id', 'b', 'text', '60 days'), jsonb_build_object('id', 'c', 'text', '90 days'), jsonb_build_object('id', 'd', 'text', 'There is no time limit')), 'correctAnswer', 'b', 'explanation', 'A discrimination complaint must be filed with MSHA within 60 days of the retaliatory act.'),
    jsonb_build_object('id', 'q45', 'question', 'The official MSHA form used to document and certify your training is the:', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Form 2000-124'), jsonb_build_object('id', 'b', 'text', 'Form 7000-2'), jsonb_build_object('id', 'c', 'text', 'Form 5000-23'), jsonb_build_object('id', 'd', 'text', 'Form 1000-9')), 'correctAnswer', 'c', 'explanation', 'MSHA Form 5000-23 is the official Certificate of Training used to document all Part 46 and Part 48 training.'),
    jsonb_build_object('id', 'q46', 'question', 'Which of the following is considered a "protected activity" under Section 105(c)?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Reporting a hazardous condition to your supervisor'), jsonb_build_object('id', 'b', 'text', 'Arriving late to work'), jsonb_build_object('id', 'c', 'text', 'Arguing with a coworker about a non-work issue'), jsonb_build_object('id', 'd', 'text', 'Refusing to clean your work area')), 'correctAnswer', 'a', 'explanation', 'Reporting a hazard is a core safety right and is therefore a legally "protected activity".'),
    jsonb_build_object('id', 'q47', 'question', 'If MSHA determines your discrimination complaint was "not frivolously brought," what is the first remedy they will seek on your behalf?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'A large financial settlement'), jsonb_build_object('id', 'b', 'text', 'An order for your temporary reinstatement to your job'), jsonb_build_object('id', 'c', 'text', 'A formal apology from the mine operator'), jsonb_build_object('id', 'd', 'text', 'A promotion to a different position')), 'correctAnswer', 'b', 'explanation', 'The "not frivolously brought" standard is designed to trigger a rapid request for temporary reinstatement to get the miner back to work while the full case is investigated.'),
    jsonb_build_object('id', 'q48', 'question', 'A Miners'' Representative has the right to do which of the following without loss of pay?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Operate any piece of equipment at the mine'), jsonb_build_object('id', 'b', 'text', 'Accompany an MSHA inspector during an inspection'), jsonb_build_object('id', 'c', 'text', 'Change the mine''s safety policies'), jsonb_build_object('id', 'd', 'text', 'Approve all new hires')), 'correctAnswer', 'b', 'explanation', 'The right to accompany an MSHA inspector on "walk-around" inspections without loss of pay is a key right of the Miners'' Representative.'),
    jsonb_build_object('id', 'q49', 'question', 'You have the right to receive all required MSHA training:', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'On your own time after your shift'), jsonb_build_object('id', 'b', 'text', 'Only if you pay for it yourself'), jsonb_build_object('id', 'c', 'text', 'During normal working hours at your regular rate of pay'), jsonb_build_object('id', 'd', 'text', 'At a location chosen by you, with all expenses paid')), 'correctAnswer', 'c', 'explanation', 'The Mine Act guarantees the right to be trained during normal work hours and to be paid for that time.'),
    jsonb_build_object('id', 'q50', 'question', 'The legal standard for refusing unsafe work is that you must have a:', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Signed statement from two other miners'), jsonb_build_object('id', 'b', 'text', 'Video recording of the hazardous condition'), jsonb_build_object('id', 'c', 'text', 'Good faith, reasonable belief that a danger exists'), jsonb_build_object('id', 'd', 'text', 'Certainty that a specific MSHA standard is being violated')), 'correctAnswer', 'c', 'explanation', 'The legal standard is a "good faith, reasonable belief" of danger, not absolute certainty or knowledge of a specific regulation.')
  )
),
updated_at = now()
WHERE id = 'd4e5f6a7-b8c9-4444-5555-666677778888';