-- Add remaining 45 questions (q6-q50) to the Comprehensive Course Assessment
UPDATE lessons
SET content_data = jsonb_set(
  content_data,
  '{questions}',
  content_data->'questions' || jsonb_build_array(
    -- Questions 6-10 (Module 1 continued)
    jsonb_build_object('id', 'q6', 'question', 'The top edge of a bench or highwall is called the:', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Toe'), jsonb_build_object('id', 'b', 'text', 'Berm'), jsonb_build_object('id', 'c', 'text', 'Crest'), jsonb_build_object('id', 'd', 'text', 'Sump')), 'correctAnswer', 'c', 'explanation', 'The crest is the top edge or rim of a highwall or bench.'),
    jsonb_build_object('id', 'q7', 'question', 'A supervisor who knowingly allows a violation of a safety standard to occur can be held personally accountable because they are considered a(n):', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Competent Person'), jsonb_build_object('id', 'b', 'text', 'Agent of the Company'), jsonb_build_object('id', 'c', 'text', 'Miners'' Representative'), jsonb_build_object('id', 'd', 'text', 'MSHA Inspector')), 'correctAnswer', 'b', 'explanation', 'Supervisors are legally considered "Agents of the Company," making them and the company liable for their actions or inaction.'),
    jsonb_build_object('id', 'q8', 'question', 'The process of drilling and blasting is most commonly associated with which type of mining operation?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Shell Dredging'), jsonb_build_object('id', 'b', 'text', 'Surface Stone (Limestone) Quarry'), jsonb_build_object('id', 'c', 'text', 'Surface Clay Mine'), jsonb_build_object('id', 'd', 'text', 'Sand & Gravel Operation')), 'correctAnswer', 'b', 'explanation', 'Hard rock like limestone must be fractured by drilling and blasting before it can be excavated.'),
    jsonb_build_object('id', 'q9', 'question', 'What is "overburden"?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'The finished, processed product ready for shipping'), jsonb_build_object('id', 'b', 'text', 'The valuable mineral deposit being mined'), jsonb_build_object('id', 'c', 'text', 'The layer of topsoil and non-valuable rock that must be removed to access the mineral deposit'), jsonb_build_object('id', 'd', 'text', 'A haul truck that has been loaded beyond its capacity')), 'correctAnswer', 'c', 'explanation', 'Overburden is the material that lies above the valuable mineral seam and must be stripped away first.'),
    jsonb_build_object('id', 'q10', 'question', 'The fine, powdery nature of clay and colloidal phosphate makes which health hazard a primary concern?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Electrocution'), jsonb_build_object('id', 'b', 'text', 'Drowning'), jsonb_build_object('id', 'c', 'text', 'Respiratory hazards from airborne dust'), jsonb_build_object('id', 'd', 'text', 'Slips and falls')), 'correctAnswer', 'c', 'explanation', 'Fine materials like clay create airborne dust, posing a respiratory hazard like silicosis.'),
    
    -- Questions 11-20 (Module 2: Hazard Recognition)
    jsonb_build_object('id', 'q11', 'question', 'What are the three steps of the "See, Think, Act" cycle?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'See the supervisor, Think about the task, Act on instructions'), jsonb_build_object('id', 'b', 'text', 'See the hazard, Think about the consequences, Act to control the hazard'), jsonb_build_object('id', 'c', 'text', 'See the equipment, Think about production, Act quickly'), jsonb_build_object('id', 'd', 'text', 'See the problem, Think about who to blame, Act to report it')), 'correctAnswer', 'b', 'explanation', 'This three-step mental model is the core of proactive hazard recognition.'),
    jsonb_build_object('id', 'q12', 'question', 'According to MSHA fatality data, what is consistently a leading cause of fatal accidents in surface mining?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Slips, trips, and falls'), jsonb_build_object('id', 'b', 'text', 'Electrical hazards'), jsonb_build_object('id', 'c', 'text', 'Powered haulage'), jsonb_build_object('id', 'd', 'text', 'Hand tool injuries')), 'correctAnswer', 'c', 'explanation', 'MSHA data consistently shows powered haulage accidents are a leading cause of fatalities.'),
    jsonb_build_object('id', 'q13', 'question', 'What is the final, non-negotiable step that must be performed to verify a zero-energy state during a LOTO procedure?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Applying your tag to the lock'), jsonb_build_object('id', 'b', 'text', 'Notifying your supervisor that the lockout is complete'), jsonb_build_object('id', 'c', 'text', 'Attempting to start the equipment (the "Try" step)'), jsonb_build_object('id', 'd', 'text', 'Removing the key from your personal lock')), 'correctAnswer', 'c', 'explanation', 'The "Try" step is the only absolute proof that the correct energy source has been isolated and the system is at a zero-energy state.'),
    jsonb_build_object('id', 'q14', 'question', 'The primary purpose of a safety grounding conductor is to:', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Provide a connection to the earth to dissipate static electricity'), jsonb_build_object('id', 'b', 'text', 'Create a low-impedance path for fault current to quickly trip a protective device'), jsonb_build_object('id', 'c', 'text', 'Serve as a secondary neutral wire for the electrical system'), jsonb_build_object('id', 'd', 'text', 'Protect equipment from lightning strikes')), 'correctAnswer', 'b', 'explanation', 'A safety ground provides an easy path for fault current, ensuring a massive flow that trips the breaker or blows the fuse, de-energizing the circuit quickly.'),
    jsonb_build_object('id', 'q15', 'question', 'You are operating a loader at the base of a stockpile and see haul trucks dumping material directly above you. What is the primary hazard?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Dust exposure from the falling material'), jsonb_build_object('id', 'b', 'text', 'Engulfment from a potential stockpile collapse caused by undercutting'), jsonb_build_object('id', 'c', 'text', 'Noise from the haul truck alarms'), jsonb_build_object('id', 'd', 'text', 'The haul truck might back over the berm')), 'correctAnswer', 'b', 'explanation', 'Digging from the toe of a stockpile while material is being added to the top over-steepens the face and removes support, creating a severe engulfment hazard.'),
    jsonb_build_object('id', 'q16', 'question', 'You are assigned to act as a spotter for a haul truck. If you lose sight of the operator in their mirrors, what should you do?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Move closer to the truck so they can see you'), jsonb_build_object('id', 'b', 'text', 'Assume they know where you are and continue signaling'), jsonb_build_object('id', 'c', 'text', 'Immediately signal an emergency stop, as the operator must stop if they lose sight of you'), jsonb_build_object('id', 'd', 'text', 'Use the radio to tell them to stop')), 'correctAnswer', 'c', 'explanation', 'The operator must stop immediately if they lose sight of the spotter. The spotter''s primary signal in this case is to stop all movement.'),
    jsonb_build_object('id', 'q17', 'question', 'What is the "angle of repose"?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'The angle of the haul road ramp into the pit'), jsonb_build_object('id', 'b', 'text', 'The safest angle to position a ladder'), jsonb_build_object('id', 'c', 'text', 'The steepest angle at which a pile of material is stable before it collapses'), jsonb_build_object('id', 'd', 'text', 'The angle of the drill mast when drilling blast holes')), 'correctAnswer', 'c', 'explanation', 'This is the natural, stable slope of a piled material, a key concept in stockpile safety.'),
    jsonb_build_object('id', 'q18', 'question', 'You are on foot and need to approach a large haul truck. What must you do before getting close to the vehicle?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Honk the horn of your pickup truck to get the operator''s attention'), jsonb_build_object('id', 'b', 'text', 'Assume the operator sees you because you are wearing high-visibility clothing'), jsonb_build_object('id', 'c', 'text', 'Wait until the operator is on a break'), jsonb_build_object('id', 'd', 'text', 'Make positive, direct eye contact with the operator and receive a clear signal acknowledging your presence')), 'correctAnswer', 'd', 'explanation', 'Due to massive blind spots, you must never assume an operator sees you. Positive eye contact and a clear signal are required before approaching.'),
    jsonb_build_object('id', 'q19', 'question', 'Tension cracks running parallel to the crest of a highwall are a primary indicator of what?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'A recent blast'), jsonb_build_object('id', 'b', 'text', 'The presence of valuable minerals'), jsonb_build_object('id', 'c', 'text', 'Impending ground failure'), jsonb_build_object('id', 'd', 'text', 'A stable, well-compacted bench')), 'correctAnswer', 'c', 'explanation', 'Tension cracks indicate the ground is pulling apart and a section of the highwall is at risk of failure.'),
    jsonb_build_object('id', 'q20', 'question', 'Before performing maintenance on a conveyor belt, in addition to LOTO, what critical step must be taken to control stored energy?', 'type', 'multiple-choice', 'options', jsonb_build_array(jsonb_build_object('id', 'a', 'text', 'Wash the belt with water'), jsonb_build_object('id', 'b', 'text', 'Block the belt against motion to release tension from the take-up system'), jsonb_build_object('id', 'c', 'text', 'Loosen the bolts on the drive pulley'), jsonb_build_object('id', 'd', 'text', 'Reverse the direction of the belt for a few seconds')), 'correctAnswer', 'b', 'explanation', 'The take-up system on a conveyor stores a large amount of mechanical energy. The belt must be blocked against motion to release this tension before maintenance.')
  )
),
updated_at = now()
WHERE id = 'd4e5f6a7-b8c9-4444-5555-666677778888';