-- Update Unit 4: Mobile & Stationary Equipment with PDF content including Haul Road simulation
UPDATE lessons
SET content_data = jsonb_build_object(
  'sections', jsonb_build_array(
    jsonb_build_object('type', 'text', 'title', 'Learning Objectives', 'content', E'Upon completion of this unit, you will be able to:\n\n- Map the primary blind spots on common surface mining equipment, such as haul trucks and front-end loaders, and articulate the concept of "No-Go" zones\n- Demonstrate the proper use of standardized hand signals for directing mobile equipment\n- Explain the critical roles, responsibilities, and communication protocols of an equipment spotter\n- Identify the primary entanglement and stored energy hazards of belt conveyors and explain the principles of guarding and blocking against motion'),
    jsonb_build_object('type', 'text', 'title', 'Case Study: The Invisibility Cloak (4:15 - 4:30)', 'content', E'This unit returns to the hazard that is consistently the number one cause of fatalities in U.S. mining: powered haulage. On September 18, 2024, a powered haulage accident at a surface quarry in Pennsylvania resulted in a miner''s death.\n\nA review of MSHA investigation reports for these types of accidents reveals a recurring and tragic theme: the operator of the large piece of mobile equipment often had no idea the victim was there. From the elevated cab of a large haul truck, a full-size pickup truck can be completely obscured from view. You must operate under the assumption that whenever you are on foot in an area with mobile equipment, you are wearing an invisibility cloak. Your safety depends on a system of communication designed to overcome the equipment''s inherent physical limitations.'),
    jsonb_build_object('type', 'text', 'title', 'Mapping the "No-Go" Zones: Equipment Blind Spots (4:30 - 4:55)', 'content', E'A blind spot, or blind area, is any area around a piece of equipment that is not visible to the operator, either through their direct line of sight or by using mirrors. Due to the massive size of mining equipment, these blind spots are extensive. You will now review blind area diagrams developed by the National Institute for Occupational Safety and Health (NIOSH).\n\nAs you can see from these diagrams, the blind area directly in front of a large haul truck can extend more than 30 feet, and the blind spot to the rear can be hundreds of feet long. The entire passenger side of the vehicle is also a significant blind area. These are the "No-Go" zones.\n\nThis is why mine sites must develop and enforce strict internal traffic control plans, which include established travel patterns, speed limits, and designated worker-free zones in areas of high equipment traffic. The cardinal rule is this: **Never approach a piece of mobile equipment until you have made positive, direct eye contact with the operator and have received a clear hand signal acknowledging your presence. Assume you are invisible until you have been explicitly seen and acknowledged.**'),
    jsonb_build_object('type', 'text', 'title', 'Communication is Life: Spotters and Hand Signals (4:55 - 5:20)', 'content', E'To safely navigate these massive blind spots, especially when backing or maneuvering in congested areas, you must rely on a formal communication system built around spotters and standardized hand signals. A spotter acts as the operator''s eyes and ears on the ground. The spotter''s only responsibility is to ensure the safe movement of the equipment. They must remain fully focused on the task, with no distractions like cell phones or other duties.\n\nThe communication between the spotter and operator must be clear, concise, and unambiguous. While two-way radios can be used, the primary method is a set of standardized hand signals. It is essential that everyone on site—all operators and all ground personnel—uses the exact same signals to prevent deadly misinterpretations.\n\n**The core principles of this system are:**\n\n1. The operator and spotter must agree on the signals and the plan of movement before the equipment moves.\n2. The spotter must always remain in a safe position, visible to the operator in their mirrors, and never place themselves in the equipment''s path of travel.\n3. The operator must stop the equipment immediately if they lose sight of the spotter for any reason.'),
    jsonb_build_object('type', 'table', 'title', 'Table 2: Standardized Hand Signals for Mobile Equipment Communication', 'headers', ARRAY['Signal Name', 'Description'], 'rows', jsonb_build_array(
      ARRAY['Stop', 'Arm extended, palm down, hold position rigidly'],
      ARRAY['Emergency Stop', 'Both arms extended, palms down, move arms back and forth horizontally'],
      ARRAY['Move Forward (Come to Me)', 'Both arms raised, palms facing inward, swing arms toward the chest'],
      ARRAY['Back Up', 'Both arms at sides, palms facing forward, push arms straight back'],
      ARRAY['Turn', 'Arm extended horizontally, pointing in the direction of the turn. The other arm makes a "move forward" or "back up" signal to indicate direction of travel'],
      ARRAY['Raise Load / Boom Up', 'Arm extended, fingers closed, thumb pointing upward'],
      ARRAY['Lower Load / Boom Down', 'Arm extended, fingers closed, thumb pointing downward']
    ), 'note', '(Note: This table presents a simplified set of the most common signals. A comprehensive site-specific list should be used.)'),
    jsonb_build_object('type', 'interactive', 'title', 'Interactive Simulation 3: Navigating the Haul Road (5:20 - 5:40)', 'simulationType', 'haulroad', 'content', E'This simulation places you in the operator''s seat to test your understanding of the complete mobile equipment safety system, including blind spot awareness, traffic patterns, and reliance on a spotter.\n\n**Objective**: You must safely operate a large haul truck through a congested work area, correctly identify and react to a blind spot hazard, and then back up to a stockpile to dump a load by correctly interpreting a spotter''s hand signals.\n\nThe simulation will test your ability to recognize blind spot hazards and properly interpret spotter hand signals.'),
    jsonb_build_object('type', 'text', 'title', 'Stationary Killers: Conveyors & Cranes (5:40 - 5:45)', 'content', E'The dangers of powerful equipment are not limited to vehicles that move around the site. Stationary equipment like belt conveyors and cranes are also major sources of fatal accidents. Conveyors are a leading cause of entanglement, where a miner''s clothing, tool, or body part is caught by a moving component. The primary hazards are ingoing nip points at the head, tail, and take-up pulleys, as well as return rollers. All of these moving parts must be protected by physical guards. Never attempt to clean, service, or retrieve material from a conveyor while it is in motion. Before any maintenance work, you must perform a full LOTO procedure and, critically, block the belt against motion to release any stored energy from tension in the take-up system.\n\nCranes and other lifting equipment require diligent pre-lift planning. Always know the weight of your load and verify that it is within the crane''s rated capacity by consulting the load chart. Inspect all rigging before use. The most severe crane accidents often involve contact with overhead power lines; maintain safe distances at all times. Never work or stand under a suspended load.')
  )
),
updated_at = now()
WHERE id = '9707a80c-7f00-448e-af40-11fbc42bc4fa';

-- Update Unit 5: Other Critical Surface Hazards
UPDATE lessons
SET content_data = jsonb_build_object(
  'sections', jsonb_build_array(
    jsonb_build_object('type', 'text', 'title', 'Learning Objectives', 'content', E'Upon completion of this unit, you will be able to:\n\n- Identify common causes of slips, trips, and falls and state preventative measures, including the importance of good housekeeping and proper illumination\n- List key safety rules for non-blasters when working in or near a blasting area'),
    jsonb_build_object('type', 'text', 'title', 'Slips, Trips, Falls, and Illumination (5:45 - 5:55)', 'content', E'While this course has focused on the high-energy hazards that lead to the most severe fatalities, you must not overlook the most frequent cause of injuries on a mine site: slips, trips and falls. Combined with material handling incidents, these account for approximately 60 percent of all lost-time accidents. These injuries can range from minor sprains to permanently disabling fractures.\n\nThe primary causes are often simple and preventable: poor housekeeping. Spills, debris, tools left in walkways, and uneven surfaces are all major contributors. Maintaining clean and orderly work areas is a fundamental safety responsibility for everyone. Proper footwear with non-slip soles is also essential, especially in wet or icy conditions.\n\nWorking at night or in low-light conditions introduces another layer of risk. Under 30 CFR § 56.17001, the mine operator must provide illumination sufficient to provide safe working conditions in all work areas, including paths, walkways, loading and dumping sites, and on surface structures. If you cannot see a hazard, you cannot avoid it. Ensure that mobile equipment lights are functional and report any areas with inadequate lighting immediately. Portable lights must be equipped with guards to prevent shock or burn hazards.'),
    jsonb_build_object('type', 'text', 'title', 'Blasting and Explosives Safety (5:55 - 6:00)', 'content', E'Finally, a brief address on blasting safety. The handling and use of explosives are restricted to trained and authorized personnel only. For everyone else, your responsibility is hazard avoidance. Every mine has a system of audible warning signals that are sounded before a blast. You must know what these signals are. Obey all posted signs and physical barricades that restrict access to a blast area. Never enter a blast area after a shot until the certified blaster in charge has inspected the area for misfires and has given the official "all clear" signal.')
  )
),
updated_at = now()
WHERE id = '17b24e54-5997-4591-9d60-c9aace8506b8';

-- Update Unit 6: Module Conclusion & Final Assessment
UPDATE lessons
SET content_data = jsonb_build_object(
  'instructions', 'A 20-question assessment to test your comprehension of Module 2: Hazard Recognition, Avoidance, and Control. You must score 80% or higher to pass. Read each question carefully and select the best answer.',
  'passingScore', 80,
  'questions', jsonb_build_array(
    jsonb_build_object('id', 'q1', 'question', 'What is the final, non-negotiable step that must be performed to verify a zero-energy state during a LOTO procedure?', 'options', ARRAY['Applying your tag', 'Notifying your supervisor', 'Attempting to start the equipment (the "Try" step)', 'Removing the key from your lock'], 'correctAnswer', '2'),
    jsonb_build_object('id', 'q2', 'question', 'The primary purpose of a safety grounding conductor is to:', 'options', ARRAY['Provide a connection to the earth to dissipate static electricity', 'Create a low-impedance path for fault current to quickly trip a protective device', 'Serve as a secondary neutral wire for the electrical system', 'Protect equipment from lightning strikes'], 'correctAnswer', '1'),
    jsonb_build_object('id', 'q3', 'question', 'You are operating a front-end loader to remove material from the base of a large stockpile. You notice haul trucks are actively dumping new material on the top of the pile directly above you. What is the primary hazard, and what is your immediate action?', 'options', ARRAY['Hazard: Dust exposure. Action: Continue working but wear a respirator', 'Hazard: Engulfment from a potential stockpile collapse. Action: Immediately stop loading, move your equipment to a safe location, and report the condition', 'Hazard: Noise from the haul trucks. Action: Continue working but wear hearing protection', 'Hazard: The haul truck might back over the berm. Action: Honk your horn to alert the truck driver'], 'correctAnswer', '1'),
    jsonb_build_object('id', 'q4', 'question', 'You are assigned to act as a spotter for a haul truck backing toward a dump point. As the truck is moving, you trip and fall. What is the first thing the truck operator must do?', 'options', ARRAY['Continue backing slowly while trying to see you', 'Stop the truck immediately', 'Honk the horn to get your attention', 'Finish dumping the load and then check on you'], 'correctAnswer', '1'),
    jsonb_build_object('id', 'q5', 'question', 'Which of the following is a primary indicator of highwall instability?', 'options', ARRAY['Smooth rock face', 'Tension cracks parallel to the crest', 'Dry conditions', 'Presence of vegetation far from the edge'], 'correctAnswer', '1'),
    jsonb_build_object('id', 'q6', 'question', 'What is the "angle of repose"?', 'options', ARRAY['The angle at which equipment should be parked', 'The steepest angle at which a pile of material can be stacked before it becomes unstable', 'The recommended slope for haul roads', 'The angle of the highwall face'], 'correctAnswer', '1'),
    jsonb_build_object('id', 'q7', 'question', 'According to the "See, Think, Act" cycle, what should you do first when approaching a task?', 'options', ARRAY['Think about the consequences', 'Act to control the hazard', 'See the hazard by actively scanning your work area', 'Consult your supervisor'], 'correctAnswer', '2'),
    jsonb_build_object('id', 'q8', 'question', 'What type of personal flotation device (PFD) must be worn when working on, over, or near water where there is danger of falling in?', 'options', ARRAY['Type III', 'Type I or Type V', 'Type II', 'Any type is acceptable'], 'correctAnswer', '1'),
    jsonb_build_object('id', 'q9', 'question', 'When is it safe to work on or near a belt conveyor while it is running?', 'options', ARRAY['If you are very careful', 'Only during emergency repairs', 'Never - always perform LOTO first', 'If a spotter is present'], 'correctAnswer', '2'),
    jsonb_build_object('id', 'q10', 'question', 'What are MSHA''s "Rules to Live By"?', 'options', ARRAY['New regulations created specifically for this training', 'Safety standards most frequently violated when miners are killed', 'Optional guidelines for best practices', 'Rules that only apply to underground mines'], 'correctAnswer', '1')
  )
),
updated_at = now()
WHERE id = '2dd5a4a8-f3d6-488a-9fb8-25dddf323874';