-- Insert lessons for Module 2: Emergency Procedures & First Aid Review
INSERT INTO public.lessons (module_id, title, description, type, order_index, duration_minutes, is_required, content_data)
VALUES 
  ('9e70a2e3-832b-459c-a914-a7db12c1e005', 'Introduction: The Survival Mindset', 'Welcome to the most critical ninety minutes of your training year. This module assumes the accident has already happened.', 'document', 1, 10, true, '{"content": "# The Survival Mindset\n\n**Welcome to the most critical ninety minutes of your training year.**\n\nMost safety training tells you how to prevent an accident. This module is different. **This module assumes the accident has already happened.**\n\nThe alarm is blaring. Smoke is filling the cab. A colleague is pinned against a conveyor. In these moments, your higher brain functions—logic, reasoning, reading—shut down. You revert to your lowest level of training.\n\n> If that training is just a checklist you memorized to pass a quiz, you will panic.\n> \n> If it is a survival reflex, you will act.\n\n## Today, you are not just a miner; you are the First Responder.\n\n### The \"Fatal Six\" Reality\n\nThis module covers the critical response protocols that save lives when seconds count:\n\n1. **Mine Emergency Response Plan (MERP)** - The Bird Dog Protocol\n2. **Radio Discipline** - Seizing control during crisis\n3. **Fire Survival** - Mobile equipment fire response\n4. **Lightning & Blasting Safety** - The 30/30 Rule\n5. **Crush Syndrome** - The toxin trap\n6. **Hemorrhage Control** - Tourniquet application"}'),
  
  ('9e70a2e3-832b-459c-a914-a7db12c1e005', 'The Bird Dog Protocol', 'Learn the MERP protocol for guiding emergency responders through the mine site.', 'interactive', 2, 15, true, '{"simulationType": "birddog", "content": "Interactive simulation: Guide the ambulance through the mine site using the Bird Dog Protocol."}'),
  
  ('9e70a2e3-832b-459c-a914-a7db12c1e005', 'Radio Discipline: Break, Break, Break', 'Master the universal interrupt phrase and emergency radio protocol.', 'interactive', 3, 10, true, '{"simulationType": "radio", "content": "Interactive training: Learn to seize control of the radio channel during emergencies."}'),
  
  ('9e70a2e3-832b-459c-a914-a7db12c1e005', 'Fire in the Pit: Mobile Equipment Survival', 'Learn fire suppression actuation and the critical \"Don''t Open the Hood\" rule.', 'interactive', 4, 15, true, '{"simulationType": "firesuppression", "content": "Interactive simulation: Respond to a haul truck fire emergency."}'),
  
  ('9e70a2e3-832b-459c-a914-a7db12c1e005', 'Lightning & Blasting: The 30/30 Rule', 'Understand lightning safety near blasting operations and the Ground Potential Rise danger.', 'document', 5, 10, true, '{"content": "# Lightning & Blasting Safety\n\n## Scenario: The Invisible Web\n\nYou are on the blast crew. You''ve loaded 50 holes. The sky turns dark. You see a flash of lightning. You count: \"One... Two... Three... Ten.\" Thunder rumbles.\n\n## The 30/30 Rule\n\nSound travels 1 mile in 5 seconds. A 10-second count means the strike was only **2 miles away**.\n\n### The Rule:\n- If the count is **less than 30 seconds**, you are in the kill zone (within 6 miles)\n- **Suspend operations immediately**\n\n### The Wait:\n- You must wait **30 minutes** after the last thunderclap before returning\n- The \"trailing anvil\" of a storm can throw a \"bolt from the blue\" miles behind the rain\n\n---\n\n## The Myth of \"Non-Electric\" Safety\n\nYour foreman says: *\"Don''t worry, we''re using Shock Tube (non-electric). It can''t be set off by lightning.\"*\n\n### The Reality: **He is wrong.**\n\n**The Mechanism:** Lightning creates a massive Ground Potential Rise (GPR). It energizes the earth itself.\n\n**The Danger:** Even plastic shock tube creates a path. The heat, the shockwave, or the static arc from a nearby strike can initiate the tube.\n\n> If the holes are loaded, the blast area is a bomb waiting for a trigger.\n\n**Action: Evacuate immediately.**"}'),
  
  ('9e70a2e3-832b-459c-a914-a7db12c1e005', 'Crush Syndrome: The Toxin Trap', 'Critical first aid for entrapment injuries - when to wait for paramedics.', 'interactive', 6, 15, true, '{"simulationType": "crush", "content": "Interactive scenario: A worker is trapped under heavy equipment."}'),
  
  ('9e70a2e3-832b-459c-a914-a7db12c1e005', 'Hemorrhage Control & Cement Burns', 'Tourniquet application and chemical burn treatment protocols.', 'document', 7, 10, true, '{"content": "# Hemorrhage Control & Chemical Burns\n\n## Hemorrhage: The Tourniquet Revolution\n\n### Scenario:\nA high-pressure line snaps and slices a coworker''s arm. The blood is **bright red and spurting** (arterial bleed).\n\n### The Action:\n\n1. **High and Tight:** Place tourniquet as high on the limb as possible (armpit or groin), over the clothes\n2. **The Pain Truth:** You must tighten the windlass until bleeding stops. This will hurt more than the injury. Tell the victim: *\"This is going to hurt, but it will save your life.\"*\n3. **The Mark:** Write \"T\" and the time on their forehead\n\n---\n\n## Cement Burns: The Chemical Lie\n\n### Scenario:\nYou are pouring a concrete pad. Wet cement slops over your boot. It feels cool and wet. It doesn''t hurt. You keep working for 4 hours.\n\n### The Chemistry:\n\nWet cement contains **Calcium Oxide**. When mixed with sweat, it becomes **Calcium Hydroxide**—a strong alkali (pH 12-13).\n\n**Saponification:** Unlike acid, which burns instantly, alkali turns the fats in your skin into soap. It liquefies your skin barrier. Because it kills the nerve endings, **there is no pain warning**.\n\n**The Damage:** By the time you feel it, it has eaten down to the bone.\n\n### The Fix:\n- **Water, Water, Water**\n- Vinegar (weak acid) can neutralize, but never delay washing to look for it\n- **Flush for 20 minutes minimum**"}'),
  
  ('9e70a2e3-832b-459c-a914-a7db12c1e005', 'Module 2 Assessment', 'Test your knowledge of emergency procedures and first aid.', 'quiz', 8, 15, true, '{"passingScore": 80, "instructions": "Answer all questions to complete this module. You need 80% to pass.", "questions": [{"id": "q1", "question": "What is the purpose of the Bird Dog protocol?", "options": ["To track wildlife near the mine", "To physically guide emergency responders through the mine site", "To monitor radio frequencies", "To inspect equipment before shifts"], "correctAnswer": "1"}, {"id": "q2", "question": "What phrase seizes control of a radio channel during an emergency?", "options": ["Mayday, Mayday, Mayday", "Break, Break, Break", "Emergency, Emergency, Emergency", "Help, Help, Help"], "correctAnswer": "1"}, {"id": "q3", "question": "Why should you NEVER open the hood of a burning vehicle?", "options": ["The hood is too hot to touch", "Fresh oxygen causes backdraft/flashover", "The fire suppression system needs the hood closed", "It voids the equipment warranty"], "correctAnswer": "1"}, {"id": "q4", "question": "According to the 30/30 Rule, when should you evacuate a blast area during lightning?", "options": ["When you see lightning within 30 feet", "When thunder follows lightning in less than 30 seconds", "When 30% of the sky is cloudy", "After 30 minutes of rain"], "correctAnswer": "1"}, {"id": "q5", "question": "A worker has been trapped under equipment for 25 minutes. What should you do?", "options": ["Lift the weight immediately to free them", "Leave the weight on and wait for paramedics with IV fluids", "Move them to a comfortable position", "Apply a tourniquet to the trapped limb"], "correctAnswer": "1"}]}');